### ISSUE TITLE
i18n-lang-js-chunks.js is deprecated

### ISSUE THREAD

**Issue by Shuhrat** [enb-make/enb#141]
Updated `enb`, in my make file I use tech [i18n-lang-js-chunks.js](https://github.com/enb-make/enb/blob/master/techs/i18n-lang-js-chunks.js) which is deprecated in new version. 
Could you please point me to the alternative tech?

Thank you!

**Comment by andrewblond** [comment]
Move tech to `enb-bembundle` package: https://github.com/enb-make/enb-bembundle/pull/3.
Deprecated tech in this package: https://github.com/enb-make/enb/pull/173.
