### ISSUE TITLE
Не включать блок при объявлении tech-зависимости от элемента

### ISSUE THREAD

**Issue by isquariel** [enb-make/enb#166]
Когда в `someblock.deps.js` объявляется зависимость вида
```js
{
    block: 'foo',
    elem: 'bar',
    tech: 'sometech'
}
```
хочется, чтобы в `foo__bar` приезжал, а `foo` не приезжал (если он не объявлен отдельно). Конкретный кейс: блок генерируется на сервере, но на клиенте у него могут появляться дополнительные элементы. BH-шаблон блока на клиенте не нужен, а вот шаблоны некоторых его элементов — нужны. В документации bem-tools, кстати, [так и написано](http://ru.bem.info/tools/bem/bem-tools/depsjs/#Подключение-только-элемента).

**Comment by mdevils** [comment]
Привет.

Спасибо, за предложение.

BEM-технологии более в пакете `enb` не поддерживаются. Они переехали в пакет `enb-bem-techs` (https://github.com/enb-bem/enb-bem-techs).

**Comment by isquariel** [comment]
Спасибо, оставлю тут ссылку на новый тикет: https://github.com/enb-bem/enb-bem-techs/issues/102
