### ISSUE TITLE
Deprecate bem techs

### ISSUE THREAD

**Issue by andrewblond** [enb-make/enb#169]
* [x] `bemdecl-from-bemjson`
* [x] `bemdecl-from-deps-by-tech`
* [x] `bemdecl-merge`
* [x] `bemdecl-provider`
* [x] `bemdecl-test`
* [x] `deps-merge`
* [x] `deps-old`
* [x] `deps-provider`
* [x] `deps-subtract`
* [x] `deps`
* [x] `files`
* [x] `levels`

**Comment by tarmolov** [comment]
I use `bemdecl-test` tech for my unit tests. What should I use instead of ` `bemdecl-test` tech?

**Comment by blond** [comment]
The `bemdecl-test` tech has not been transferred to other packages. I do not have a good implementation that I would recommend.

You can use your own implementation at the level of their projects or create package for these tasks.

I know of packages to build and run tests:
* [enb-bem-specs](https://github.com/enb-bem/enb-bem-specs)
* [enb-bem-tmpl-specs](https://github.com/enb-bem/enb-bem-tmpl-specs)
* [enb-bem-node-specs](https://github.com/dragn/enb-bem-node-specs)

**Comment by tarmolov** [comment]
Ok. Thank you. I'll take a look at these packages.
