### ISSUE TITLE
Invalid styl file forces server to not responde

### ISSUE THREAD

**Issue by zxqfox** [enb-make/enb#211]
How to repeat:
- With a project-stub (or `yo bem-stub`) make a `common.blocks/page/page.styl` with mixed tabs and spaces as indent.
- Force to render page

Result: Timeout + error mess in stderr?;
Expected result: Stack trace in the response + error mess in stderr.

**Comment by zxqfox** [comment]
I think there are two problems: 1 in styl tech, and the second — in the server itself. So I'll file the same issue in `styl` tech repo.
Ref: https://github.com/enb-make/enb-stylus/issues/29

**Comment by blond** [comment]
Bug was`t reproduced — https://github.com/enb-make/enb-stylus/issues/29
