### ISSUE TITLE
Semicolon as chunks delimiter in js tech

### ISSUE THREAD

**Issue by hsalkaline** [enb-make/enb#214]
Currently enb uses `justJoinFilesWithComments` in `js` and `js-i18n` techs to concatenate javascript sources. This function separates files with `/*begin*/` and `/*end*/` markers.

Other build systems use semicolon as delimeter, when dealing with js files:
* bem-tools  https://github.com/bem/bem-tools/blob/support/0.9.x/lib/techs/js.js
* grunt suggests to use semicolon as separator of js files https://www.npmjs.com/package/grunt-contrib-concat#separator

The reason for using semicolon is clear: we prevent content of some file to be treated as part of function call

Consider following example: lets say, we have 2 files with following content:
##### file1.js
```
(function(){/*Some code in IIF*/}())
```
##### file2.js
```
(function(){/*Another code in IIF*/}())
```

Concatenation with semicolon would work as expected
```
(function(){/*Some code in IIF*/}());(function(){/*Another code in IIF*/}())
```

Whereas concatenation without semicolon
```
(function(){/*Some code in IIF*/}())(function(){/*Another code in IIF*/}())
```
would produce error

As a workaround, I now use `js-with-semicolons` tech which is exactly like `js` tech, with exception of that  `.justJoinFilesWithComments()` call is replaced with
```
.justJoinFiles(function (filename, data) {
    var fn = this.node.relativePath(filename);
    return '/* begin: ' + fn + ' *' + '/\n' + data + '\n;/* end: ' + fn + ' *' + '/';
})
```
But, I belive that everyone would benefit from having above change "out of the box". 

The question is: would PR with the described change be accepted, or would it be recognized as breaking change?

**Comment by mdevils** [comment]
`justJoinFilesWithComments` can be used for both JS and CSS right now. Your change will break CSS support.

**Comment by hsalkaline** [comment]
`justJoinFilesWithComments` should be left as is. I propose changes in `js.js` and `js-i18n.js`

**Comment by blond** [comment]
@hsalkaline use [browser-js](https://github.com/enb-make/enb-js/blob/master/api.ru.md#browser-js) tech from `enb-js` package with [iife](https://github.com/enb-make/enb-js/blob/master/api.ru.md#iife) option.
