### ISSUE TITLE
Откладывание старта технологии до сборки определенных таргетов

### ISSUE THREAD

**Issue by aliosv** [enb-make/enb#219]
@andrewblond,
Задача: фризить урлы в bemtree в нодовом приложении.
Проблема: фриз должен стартануть после сборки статики.
Решение:
вместо 
```[borschik, { source : '?.bemtree.js', target : '_?.bemtree.js', freeze : true, tech : 'js' }]```
вот такая обертка
```
[require('enb-borschik/node_modules/inherit')(borschik, {
    build : function() {
        var _this = this,
            _base = this.__base,
            args = arguments,
            depsTargets = ['_?.js', '_?.css'].map(function(target) {
                return this.node.unmaskTargetName(target);
            }, this);

        return this.node.requireSources(depsTargets).then(function() {
            return _base.apply(_this, args);
        });
    }
}), { source : '?.bemtree.js', target : '_?.bemtree.js', freeze : true, tech : 'js' }]
```

1) Есть ли более подходящее решение?
2) Cтоит выделить обертку в отдельную технологию?

**Comment by andrewblond** [comment]
Привет! 

Думаю имеет смысл подумать над расширением API технологии `borschik`. Нужно добавить опцию, которая будет принимать таргеты, которые нужно подождать (['_?.js', '_?.css']).

**Comment by aliosv** [comment]
тогда нужно добавлять в опцию и https://github.com/bem/borschik/blob/master/lib/freeze.js#L512
чтобы сразу все работало из make.js?

**Comment by andrewblond** [comment]
> тогда нужно добавлять в опцию

Думаю, что да. Можешь завести таски в `enb-borschik` и описать реальные кейсы, чтобы было понятнее?

**Comment by aliosv** [comment]
да

**Comment by aliosv** [comment]
https://github.com/enb-make/enb-borschik/issues/13

**Comment by tormozz48** [comment]
@blond Можно ли закрыть эту задачу?

**Comment by blond** [comment]
@tormozz48, да. Исправлено в `enb-borschik@2.0.0`.
