### ISSUE TITLE
Метод runTechAndGetContent работает с ошибкой

### ISSUE THREAD

**Issue by sipayRT** [enb-make/enb#224]
После отрабатывания метода `runTechAndGetContent` промис возвращается раньше, чем результат был записан в файл.

**Comment by tormozz48** [comment]
Где это можно воспроизвести? По коду пока непонятно почему так получается

**Comment by blond** [comment]
@tormozz48 Я взялся переносить моки из `enb` пакета (#225). Обновлю зависимости и т.д., и только потом имеет смысл воспроизводить.

**Comment by blond** [comment]
После перехода на `mock-enb` не воспроизводится.
