### ISSUE TITLE
Remove nested describe blocks from fs libs tests

### ISSUE THREAD

**Issue by SwinX** [enb-make/enb#280]
For FS libs all tests wrapped in something like this

``` javascript
describe('lib', function () {
    describe('fs', function () {
        describe('async-fs', function () {
...
```

It's becoming hard to read report generated by mocha with a lot of this garbage.
Propose to remove it replacing with something like

``` javascript
describe('fs/async-fs', function () {
...
```

**Comment by blond** [comment]
:+1:
