### ISSUE TITLE
Explanation of ENB abbreviation

### ISSUE THREAD

**Issue by SwinX** [enb-make/enb#339]
Right now no one certain about the meaning of ENB abbreviation. So right now it's a good time to stop this! 

/cc @blond @j0tunn @tormozz48

**Comment by SwinX** [comment]
Proposing acronym **E**nb **N**ot **B**undler

**Comment by blond** [comment]
@mdevils, поделишься знанием? =)

**Comment by vtambourine** [comment]
This abbreviation makes sure no one confuse ENB with BEM tools, because ENB is not BEM.

**Comment by SwinX** [comment]
Thank you!

**Comment by j0tunn** [comment]
Может в README внести?
