### ISSUE TITLE
Добавить технологию `write-file`

### ISSUE THREAD

**Issue by pavelpower** [enb-make/enb#425]
# enb/techs/write-file

Технология генерирование файла указав контент в виде типа String или Bufer.

Одновременно выполнить функцию provide (то, что делает file-provide) для платформы make.

## Зачем это нужно?

Как пример использования такой технологии приведу задачу из моего проекта.

Задача: к проекту посредством сабмодуля гит подключается слой переопределения с набором блоков.
Весь JavaScript код из этих блоков должен быть собран в один модуль `extention-apps`. 
И добавлен в модульную систему как один модуль.

Вот пример файла который нужно сгенерировать:

`common.blocks/external-apps/external-apps.js`

```javascript
modules.define('external-apps', function(provide, apps) {

    apps = apps || {};

    apps['app-tetris'] = {
        init: funciton () {
            //...
        }
    };

    provide(apps);
});

modules.define('external-apps', function(provide, apps) {

    apps = apps || {};

    apps['app-footboal'] = {
        init: funciton () {
            //...
        }
    };

    provide(apps);
});

// more apps ....

```

Как это можно реализовать?

А вот так:

```javascript
var techs = require('enb-bem-techs'),
    writeFile = rewuire('enb-write-file'),
    js = require('enb/techs/js');

module.exports = function (config) {

    var contentBemdeclFile,
        apps = FS.readdirSync('./external-apps'); // read git-submodules layer

    // create content for "external-apps.bemdecl.js"
    apps = apps.filter(function (name) {
        return name !== 'readme.md';
    }).map(function (name) {
        return '{name: "' + name + '"}'
    }).join(',\n');

    contentBemdeclFile = ['exports.blocks = [\n', apps, '\n];'].join('\n');

    config.node('common.blocks/external-apps', function (nodeConfig) {

        nodeConfig.addTechs([
            [techs.levels, {
                levels: [
                    {path: nodeConfig._path, check: true},
                    {path: config.resolvePath('external-apps'), check: true}
                ]
            }],

            [writeFile, {
                target: '?.bemdecl.js',
                content: contentBemdeclFile
            }],

            [techs.files, {depsFile: '?.bemdecl.js'}],

            // concat all js files to externl-apps.js
            [js, {
                target: '?.js'
            }]
        ]);

        nodeConfig.addTargets(['?.js']);
    });

}

```

**Comment by blond** [comment]
> Одновременно выполнить функцию provide (то, что делает file-provide) для платформы make.

Не совсем. Эта технология, как и любая другая просто говорит, что записала свой результат в файл.

Просто `file-provider` делает только это :)

**Comment by blond** [comment]
Ждём PR :)

**Comment by pavelpower** [comment]
@blond а почему бы не запровайдить? Т.е. даже не стоит так делать?

**Comment by blond** [comment]
Уточни, что имеешь ввиду под запровайдить :)

**Comment by pavelpower** [comment]
@blond  достаточно ли должно быт использование `enb/techs/write-file` для того, чтобы записать файл и не использовать за одно `file-provide`?

Или `file-provide` must have в цепочке подключаемых технологий?

**Comment by blond** [comment]
> достаточно ли должно быт использование enb/techs/write-file для того, чтобы записать файл и не использовать за одно file-provide?

Достаточно.

**Comment by pavelpower** [comment]
@blond что-то у меня с тестами не катит. Можешь дать информацию как с текущими технологиями добавить тест?

чтобы

```javascript
     beforeEach(function () {
         //
    });

    afterEach(function () {
         // remove file: bundles/file/file
    });

    it('should write target file to file system', function () {
        return bundle.runTech(WriteFileTech, {
                target: 'file',
                content: 'I\'m here'
            })
            .should.be.fulfilled
            .then(function () {
                console.log(resolveSpy());
                resolveSpy.should.calledWith('file.txt');
            });
    });
```

**Comment by pavelpower** [comment]
@blond 
> Ждём PR :)

https://github.com/enb-make/enb/pull/426

**Comment by blond** [comment]
Fixed in #426.
