### ISSUE TITLE
Версия 1.0.0

### ISSUE THREAD

**Issue by mdevils** [enb-make/enb#84]
В версии `1.0.0` из ENB будут извлечены различные технологии в отдельные пакеты.

Перед версией `1.0.0` будет выпущен релиз `0.x.0` с `deprecation`-варнингами и четкими инструкциями.

* xml-технологии вынесены в https://github.com/enb-make/enb-lego-xml
* stylus-технологии вынесены в https://github.com/enb-make/enb-stylus
* js-технологии для bem-core в https://github.com/enb-make/enb-diverse-js

Suggestions?

**Comment by blond** [comment]
https://github.com/enb-make/enb/releases/tag/v1.0.0
